name: hls_downloader

on:
  push:
    branches: [ "main" ]
    tags:
      - "*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - 
        name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          check-latest: true
      
      - run: go mod tidy
      - run: go mod download && go mod verify

      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOYMENT_KEY }}
